### ISSUE TITLE
RTR session crashed

### ISSUE THREAD

**Issue by sebastianw** [NLnetLabs/routinator#17]
```
Nov  7 11:07:41 noc2 routinator[93742]: The RIPE NCC Certification Repository is subject to Terms and Conditions
Nov  7 11:07:41 noc2 routinator[93742]: See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc
Nov  7 11:07:41 noc2 routinator[93742]: The RIPE NCC Certification Repository is subject to Terms and Conditions
Nov  7 11:07:41 noc2 routinator[93742]: See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc
Nov  7 11:07:57 noc2 routinator[93742]: rsync://rpki.ripe.net/repository/DEFAULT/ce/2991fc-2a43-4aac-8725-03ddfcca7cdc/1/1-PLmqwITyHkp7BlKU0rsqAUtjEw.mft: failed to load.
Nov  7 11:07:58 noc2 routinator[93742]: rsync://rpki.ripe.net/repository/DEFAULT/a6/fe114b-acb2-40c4-a856-edffb3939db7/1/4vgr8a5QpQSRpLgMNtk90WLuxug.mft: failed to load.
Nov  7 11:08:02 noc2 routinator[93742]: skipping unknown file rsync://ca.rg.net/rpki/RGnet/kk7leA2QyWB46-RxM5KVfKhI7nk.gbr
Nov  7 11:08:06 noc2 routinator[93742]: thread 'tokio-runtime-worker-1' panicked at 'index out of bounds: the len is 0 but the index is 1', /opt/rpki-validator/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.1.1/src/rtr/send.rs:223:28
Nov  7 11:08:06 noc2 routinator[93742]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
Nov  7 11:08:06 noc2 routinator[93742]: thread 'tokio-runtime-worker-1' panicked at 'index out of bounds: the len is 0 but the index is 1', /opt/rpki-validator/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.1.1/src/rtr/send.rs:223:28
Nov  7 11:08:06 noc2 routinator[93742]: thread 'tokio-runtime-worker-1' panicked at 'index out of bounds: the len is 0 but the index is 1', /opt/rpki-validator/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.1.1/src/rtr/send.rs:223:28
Nov  7 11:08:06 noc2 routinator[93742]: thread 'tokio-runtime-worker-1' panicked at 'index out of bounds: the len is 0 but the index is 1', /opt/rpki-validator/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.1.1/src/rtr/send.rs:223:28
Nov  7 11:08:06 noc2 routinator[93742]: thread 'tokio-runtime-worker-1' panicked at 'index out of bounds: the len is 0 but the index is 1', /opt/rpki-validator/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.1.1/src/rtr/send.rs:223:28
Nov  7 11:08:06 noc2 routinator[93742]: thread 'tokio-runtime-worker-1' panicked at 'index out of bounds: the len is 0 but the index is 1', /opt/rpki-validator/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.1.1/src/rtr/send.rs:223:28
Nov  7 11:08:06 noc2 routinator[93742]: thread 'tokio-runtime-worker-1' panicked at 'index out of bounds: the len is 0 but the index is 1', /opt/rpki-validator/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.1.1/src/rtr/send.rs:223:28
Nov  7 11:08:06 noc2 routinator[93742]: thread 'tokio-runtime-worker-1' panicked at 'index out of bounds: the len is 0 but the index is 1', /opt/rpki-validator/.cargo/registry/src/github.com-1ecc6299db9ec823/routinator-0.1.1/src/rtr/send.rs:223:28
```

**Comment by partim** [comment]
Thank you for the report!

We should have a fix available soon – just doing some testing on it now.

**Comment by partim** [comment]
This seems serious enough to release 0.1.2, likely later today or early tomorrow.
