### ISSUE TITLE
v0.9.0-rc1 crash on start

### ISSUE THREAD

**Issue by mtlnog** [NLnetLabs/routinator#556]
Hello,

I upgraded our dev validator running routinator v0.8.4-dev to v0.9.0-rc1 on Ubuntu 18.04.5 LTS and I get the following errors:

May 17 16:32:07 rpki-dev systemd[1]: routinator.service: Service hold-off time over, scheduling restart.
May 17 16:32:07 rpki-dev systemd[1]: routinator.service: Scheduled restart job, restart counter is at 75.
May 17 16:32:10 rpki-dev rpki-routinator[23754]: thread '<unnamed>' panicked at 'assertion failed: mid <= self.len()', /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/slice/mod.rs:1505:9
May 17 16:32:10 rpki-dev rpki-routinator[23754]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 17 16:32:11 rpki-dev systemd[1]: routinator.service: Main process exited, code=killed, status=6/ABRT

**rustc/rustp versions**

rustup 1.24.2 (755e2b07e 2021-05-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.52.1 (9bc8c42bb 2021-05-09)`

**Comment by partim** [comment]
Thank you for testing the release candidate! And also: yikes. Unfortunately, the output isn’t very helpful. Is there a chance you can start Routinator with `RUST_BACKTRACE=1` environment variable and post the resulting stack trace?

**Comment by mtlnog** [comment]
My bad... there you go:

```
rpki@rpki-dev:~$ RUST_BACKTRACE=full /home/rpki/.cargo/bin/routinator server
thread '<unnamed>' panicked at 'assertion failed: mid <= self.len()', /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/slice/mod.rs:1505:9
stack backtrace:
   0:     0x563b40c1f5f0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x563b40c1f5f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563b40c1f5f0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563b40c1f5f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x563b40c448ff - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x563b40c17822 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x563b40c21c75 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563b40c21c75 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563b40c21c75 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x563b40c21723 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x563b40c2227d - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x563b40c21de7 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:495:13
  12:     0x563b40c1faac - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563b40c21d79 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x563b407ba151 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x563b407ba09d - core::panicking::panic::h10ab123a4b13cc79
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
  16:     0x563b408473d7 - <routinator::collector::rrdp::RepositoryState as core::convert::TryFrom<sled::ivec::IVec>>::try_from::hd5b4a0ad249a878f
  17:     0x563b4083eb3e - routinator::collector::rrdp::Run::load_repository::h1e0ee1d796d6101b
  18:     0x563b408e0516 - routinator::collector::base::Run::repository::h1fb32ca1584e5d44
Aborted (core dumped)
```

**Comment by partim** [comment]
Thanks! Turns out I can’t count.
